### ISSUE TITLE
1st Terror from Beyond in a phase forces to choose more than 1 type of cards to discard

### ISSUE THREAD

**Issue by stefano-bragaglia** [halogenandtoast/ArkhamHorror#106]
In a Dunwich Legacy game, I ended up drawing Terror from Beyond during the Mythos phase.

I'm playing solo, so that's the only card of that type that can be drawn in such phase.

The card asks to choose one from asset, event, or skill, then each player (just me in this case) discards all the cards in their hand of that type. If another copy of the same Treachery was drawn in the current phase (not possible because I'm playing solo, it would be possible if Terror from Beyond had Surge which is not the case), two types must be chosen instead of one.

As I said, playing solo I would have to choose just one card type, but the app asks to choose a second type after the first.
Please find attached the game status.

[arkham-debug.json.gz](https://github.com/halogenandtoast/ArkhamHorror/files/9106363/arkham-debug.json.gz)

_BTW, I've sheen the Google Sheet to track the status of your tests. In Python there are tools to write tests and track if they succeed or not. Tests are typically run before committing so that the developer is notified if any change has broken the logic of the application or not. Is anything like Python's UnitTest or PyTest available for Haskell? I believe it would be highly convenient for you to have! Google says there is the Haskell Test Framework (HTF for short) but I have not idea how it works..._

**Comment by halogenandtoast** [comment]
Should be fixed in 8eacc2a27f40e1c8e01643307891554d14464d6f

I have github actions setup to automatically run my tests and alert me on failure now (recently new), but I don't yet have a lot of test coverage (because I am programming by myself and tests are less fun than new cards). I am working on getting some coverage for every card, but tests are also somewhat ceremonial to write because everything has to be an integration spec that requires setting up a relevant game state. Anyways, as I get more coverage, and try to work towards a stable release, breakage will be far less likely.

**Comment by stefano-bragaglia** [comment]
I'm not familiar with the Haskell dev environment, but glad to hear you have some kind of testing facility in place. Tested saved my sanity in more than one occasion!

I completely understand: I would focus on new cards too!

Just updated my endpoint, and the issue is solved! Thank you!
