### ISSUE TITLE
Unable to advance as Ashcan Pete in House Always Wins

### ISSUE THREAD

**Issue by wappowers** [halogenandtoast/ArkhamHorror#110]
Unable to advance on act 2b. Pink border is on the card, but nothing happens when clicked.
[arkham-debug (1).zip](https://github.com/halogenandtoast/ArkhamHorror/files/10325967/arkham-debug.1.zip)

**Comment by halogenandtoast** [comment]
Should be fixed with https://github.com/halogenandtoast/ArkhamHorror/commit/25894a4d2907f76c6bc1b0a600fc1c5e7bf10b8a but this will be part of a deploy that will surely break the current games (The Circle Undone investigators have been unkind).

The issue was that given recent changes to genCard we look at the card type to decide if we lookup a player card or an encounter card, but Peter Clover wasn't set correctly to be considered an encounter card (similar to a few other cards I fixed).
