### ISSUE TITLE
Clues reset on Prismatic Cascade?

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1105]
Not sure about this one.
I hade one Prismatic Cascade in play where I had only 1 clue left. Another Prismatic Cascade was drawn and now both cards have 3 clues. The reason I'm not sure if this caused it is that when I undo, there are still 3 clues on the original card.
Either way, something's fishy about the clues on Prismatic Cascade :-)

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/cf54b73867d0201dbfac253b6ec63286e393c7f074b89cdd984c815da178972f.json

**Comment by halogenandtoast** [comment]
Maybe you are confusing the Prismatic Cascade with the Tear Through Space that was out. It seems like 

* Act Ability
* Tear through space gets drawn (with 1 clue)
* Surge into prismatic (with 3 clues) -- THIS SURGE SHOULDN'T HAPPEN, fixed in your other report
* End of Turn
* Forced, Tear through space gets discarded
* Agenda Advances
* Another Prismatic comes into play
