### ISSUE TITLE
Can't trigger Kate's ability on skill tests

### ISSUE THREAD

**Issue by Kwaice** [halogenandtoast/ArkhamHorror#1107]
As title said

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/00136d54e9a7a81d746b98c8cba63c1d6a1a83976d2e464a4db30f4cd8851ff7.json

**Comment by halogenandtoast** [comment]
![Image](https://github.com/user-attachments/assets/77523937-8e71-46c3-81ea-a49f3de52973)

In the settings section the app automatically disables fast abilities that don't affect skill test results (mainly because I get a LOT of issues filed about how annoying it is). 

At the moment if you want to use Kate's ability you can disable this option:

View -> Settings -> Uncheck the box

You can also use the shortcut (Shift + S)

If there is a specific reason you want to activate this ability during the skill test could you let me know.
