### ISSUE TITLE
Kymani ability not allowing pickpocketing trigger

### ISSUE THREAD

**Issue by zzdldl31** [halogenandtoast/ArkhamHorror#1120]
Something about Kymani's ability is so buggy and in various times something break, and it is so hard to guess why and how it occurs

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/1c860e3dd167e07150f50a138f6e51534773fdeb46a574e57334ad0e9e5de9d0.json

**Comment by halogenandtoast** [comment]
> Something about Kymani's ability is so buggy and in various times something break, and it is so hard to guess why and how it occurs

Imagine how I feel! ha ha ha

To file the bug you don't really need to figure out what went wrong, just feel free to describe what you were trying to do and what your expectation was and that's enough for me to look into it.

In this particular case the issue is how I deal with checking the triggers on things like Pickpocketing. Basically it tries to check "does the enemy evaded match some criteria" in the case of Pickpocketing it's "any enemy" but other cards might care about details such as Traits. 

However, because Kymani's ability discards the enemy it "no longer exists" and therefor "doesn't match anything" when the game checks if Pickpocketing can be triggered. I've recently done some work to move "removed" things to a "OutOfPlay/Removed" zone, but I wasn't doing this for enemies yet. 

The upcoming fix will basically hold onto the the enemy details in this area to allow for checking, on top of that I'll be adding a short-circuit when the case is "any enemy" so it doesn't need to do a lookup in those cases. It should make things a lot more stable for evasion based triggers with Kymani.

**Comment by zzdldl31** [comment]
As a programming major, it feels fascinating to understand the causes and solutions to these bugs. I sincerely thank you for your replies and fixes, though I just have to report every bug I encounter so... looks like I will bother you more in the future!

**Comment by halogenandtoast** [comment]
@zzdldl31 no problem! I don't mind explaining the issues/solutions if you have an interest. Also please feel free to file any issue you come across, I can't fix what I don't know is broke.
