### ISSUE TITLE
Can't fight evaded swarm enemy 

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1156]
Evaded enemy "swarming 1" group. Activated Dirty Fighting to make bonus attack but can only select the host as target for the attack. Putting damage on the host doesn't defeat it since it has a card under it.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/b720467ced4de6d58b993a6b7c3d6b64c9398ff168acb2624c0db77e65fe2950.json

**Comment by halogenandtoast** [comment]
Sooooo hard to actually decide how to fix this because it's just a timing issue. If you "Skip Triggers" it will prompt you again and give you the swarm card.

The issue is when you evade one swarm enemy, it evades the group, so the first window you are getting is the host, but it's not obvious, the second window will be for that swarm card.

**Comment by halogenandtoast** [comment]
Actually I think the logic here is incorrect anyways, and fixing that will solve this issue. Only ONE swarm enemy is evaded, but they all exhaust, so the dirty fighting trigger should only happen once.
