### ISSUE TITLE
Should Jake Williams reaction trigger on another investigator's turn?

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#1160]
Triggers "When you put a location into play". In this case the Basement Hall puts locations into play and Jake is triggered but it is not Ursula who enters Basement Hall.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/cb0071f41779e3651ccf9c74fd56862edd33c5c158ff1a2f72fb7dff7c66f124.json

**Comment by halogenandtoast** [comment]
So the answer is sort of, but I'm going to make an adjustment here.

The forced ability on Basement Halls says:

> Forced - After the Basement Hall is revealed: Put the 4 set-aside Patient Confinement locations into play.

This doesn't mention which investigator should trigger this. For the put location into play trigger, I had defaulted to the lead investigator, which is why Ursula triggers here, but that isn't quite right and the players should be able to choose, so here is the "fix" coming.

The system will now consider the specific player who clicks the forced trigger, so if you wanted Ursula to benefit, you could switch to her perspective to click the forced button and you could trigger Jake. However, if you were to do this from Wilson's perspective it would not.
