### ISSUE TITLE
Dunwich Extracurriculars Last Agenda  advances too early

### ISSUE THREAD

**Issue by Eleros** [halogenandtoast/ArkhamHorror#141]
3rd Agenda should only advance once the Experiment reaches Dormitories, instead it advances immediately on the first Doom 2 threshold.
Also the Alchemical Concoction only does 2 damage.

**Comment by halogenandtoast** [comment]
Should be fixed in the next release. The issues were:

1) The forced agenda ability wasn't removing the doom and it should have
2) Alchemical concoction had a bunch of incorrect code (was using willpower instead of intellect and had an automatic +1 damage), but the +6 damage wasn't happening because of how the modifier was being applied and the concoction being removed from play. We've fixed that now.
