### ISSUE TITLE
Dunwich Undimensioned and Unseen error

### ISSUE THREAD

**Issue by Eleros** [halogenandtoast/ArkhamHorror#145]
Game doesn't put the Powder of Ibn-Ghazi into play during setup. Putting into manually into play it also doesn't enter play with any clues on it.

Also, the list of weaknesses contains non-basic ones. I got Wracked by Nightmares for one, Lost Soul for another (lol), and Across Space and Time for the last.

And looks like Esoteric Formula deals 0 damage to the Broods.

Avian Thrall doesn't apply the -3 fight when attacked by spells.

Altered Beast doesn't work. Doesn't surge nor attach.

The Creature's Track encounter card doesn't give a choice to spawn the Brood, it just deals horror.

Act 2 advances as soon as no Broods are in play, even if there are still copies set aside.

I noticed that Armitage triggers on encounter cards (lol). Warren Rice triggers when investigating locations without any clues also.

**Comment by halogenandtoast** [comment]
I am able to fix all of these except the following:

> Game doesn't put the Powder of Ibn-Ghazi into play during setup. 

It shows up in play for me (it won't in standalone mode).

Fixes:

> Putting into manually into play it also doesn't enter play with any clues on it.
Turns out I never recorded who survived

> Also, the list of weaknesses contains non-basic ones. I got Wracked by Nightmares for one, Lost Soul for another (lol), and Across Space and Time for the last.

Fixed to only be basic weakness cards (also found a bunch of other areas where I made the same mistake and fixed them)

> And looks like Esoteric Formula deals 0 damage to the Broods.

Yup, I changed how I track the source of things and it was not an ability of esoteric formula rather than esoteric formula itself and this confused things

> Avian Thrall doesn't apply the -3 fight when attacked by spells.

Similar to above

> Altered Beast doesn't work. Doesn't surge nor attach.

Yeah there was an issue where the ability on it was erroring.

> The Creature's Track encounter card doesn't give a choice to spawn the Brood, it just deals horror.

I had made a mistake on how it checks for set aside cards.

> Act 2 advances as soon as no Broods are in play, even if there are still copies set aside.

same as above

> I noticed that Armitage triggers on encounter cards (lol).

Yup the matcher for "your deck" accidentally triggered on any deck

> Warren Rice triggers when investigating locations without any clues also.

Yup that window was triggering even if no tokens.

**Comment by Eleros** [comment]
> It shows up in play for me (it won't in standalone mode).
That's odd, it didn't work for me. Was playing in campaign mode. I had to use debug menu to search it up and play it. 

Great work btw. I actually much prefer this to TTS. I also finally internalized the exact steps where you can activate Lightning effects in lol.

**Comment by halogenandtoast** [comment]
@Eleros if you still have that game where it didn't show up could you export the game and upload the json file here?

**Comment by Eleros** [comment]
I finished the campaign since so you'll have to go back a bit but here ya go.

[](https://www.mediafire.com/file/zrijdhiyxa6w763/arkham-debug.json/file)

**Comment by halogenandtoast** [comment]
I can't seem to step back all the way, sometimes I can't with debug exports, if it happens again can you open a new issue, everything else should be resolved.
