### ISSUE TITLE
Using Stir the Pot against a stack of swarming enemies caused confusion

### ISSUE THREAD

**Issue by nicksephton** [halogenandtoast/ArkhamHorror#221]
Game: 43095263-0092-43a9-8f09-dea141baa883

I used Stir the Pot against a stack of 3 Inconspicuous Zoogs. 

The first took two damage but didn't die (unknown why), to this didn't trigger the forced ability.

The second took two damage and then tried to move away correctly.

The third took two damage (which I think is correct as this is three separate lots of damage?) but then the forced ability triggered again after they had moved once, causing them to move again.

**Comment by nicksephton** [comment]
Also, the last in the stack has enough damage to kill it, but it hasn't died.

**Comment by halogenandtoast** [comment]
If you damage the top zoog it's not going to die until after it's swarm ones die. However there was a bug that would prevent it from dying so that fix will be deployed soon.

**Comment by nicksephton** [comment]
I may have misunderstood swarming, but if you do 2 damage to each of them simultaneously, shouldn't they all die?

**Comment by halogenandtoast** [comment]
A slight limitation of the app is I don't know that I can apply the damage simultaneously because you'd have trigger windows and the such which have to be resolved independently. However the end result should roughly be the same now (I fixed it so that the top zoog should die if it has the necessary damage on it).

I do think I don't have a good way to not trigger the forced ability for each of them dying (aside from the host because there would be nothing left to do) because even if simultaneous you'd need to resolve 2 separate effects.

Hopefully in this case this is good enough now that the top one dies, but I will likely revisit how I handle this in the future.

**Comment by nicksephton** [comment]
I sent you an email - I'm interested in helping out if you would like the help. :)

**Comment by halogenandtoast** [comment]
Ah I missed it, I just responded!
