### ISSUE TITLE
Stuck in a Skill Test after playing Elusive

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#301]
**Provide a Game ID**
1d20ac4d-a3b3-4204-9d25-faa6652169a8
**Describe the bug**
I was doing the skill test to obtain Jazz, and I thought I was commiting Elusive to the test (but I was still in the Fast window) so it tried to play it instead. Since all I can do is move to another location, doing so makes it so that I'm in a weird loop where I can't resolve the skill test and I'm already away from the location so I can't really do anything. Also I cannot Undo playing Elusive, the most it goes back to is to when Elusive is in play and it's asking me to pick a location to move to.

**Comment by halogenandtoast** [comment]
I also can't step back. I tried the same setup (playing elusive during a parley on Jazz) and at both fast windows it works correctly for me.

It does seem like if you keep progressing until you do another skill test that one will go away. You could maybe use a couple of debug actions to get your actions back and try again (but there is not a good way to get elusive back at the moment).

Either way I can't fix this one directly (to know what went wrong) without being able to go back and it says the step is missing so maybe it failed to write to the database for some reason. I checked and this is in a transaction so it doesn't make sense for it to be out of sync.

Just in case I'm adding some locking to the tables, but since I currently can't recreate  or debug this I'll need to close this for now. If you run into it again , please reopen the issue.
