### ISSUE TITLE
Mythos Card Drawn does not Move forward

### ISSUE THREAD

**Issue by wschlundt** [halogenandtoast/ArkhamHorror#355]
https://arkhamhorror.app/#/games/8fb340e9-1c17-4615-8702-cbcbe272fded

Playing two handed through first scenario. Drew mythos card for Agnes. Ghoul appropriately engaged.  Can't seem to figure out what's not triggering it to move forward. Players each have their actions, engages are correct and can't find any highlighted pink areas to trigger.

Love your app by the way, makes it fun to get to play on a lunch break at work!

**Comment by halogenandtoast** [comment]
A few issues here, the first which will fix by refreshing once the fix is deployed.

1) So delay the inevitable is in play, but you can't see it, that is what is waiting to be activated, once the deploy is out you can refresh and it will show up

2) Unfortunately, it had some issues when playing it and it will show up on Agnes even though it's controlled by Carolyn. I fixed it being correctly played under the control of the player you choose, but unless you go back far enough you won't see this.
