### ISSUE TITLE
In The Wages of Sin I cannot move from Haunted Fields to The Gallows

### ISSUE THREAD

**Issue by kortatu** [halogenandtoast/ArkhamHorror#376]
**Provide a Game ID**
f82cbd74-4201-4dee-bf8a-be8fd1a47629

**Describe the bug**
I cannot move directly from Haunted Fields to the Gallows. If I move to Heretic's Graves, then I can do it.
<img width="935" alt="Captura de pantalla 2024-08-21 a las 18 35 49" src="https://github.com/user-attachments/assets/66a39fe1-8955-4c54-9421-fe81b4e2f473">

Instead I can move all the way to Chapel Crypt even though they are not connected.

**Comment by halogenandtoast** [comment]
I've added a fix for this, which was that the spectral location somehow had the incorrect connections. However connections are set when the location is revealed so in order to fix this you will need to "Reset" the location. Conveniently, there is a debug menu option to fix it. That menu option currently only works for unrevealed locations, but I'm pushing out an update that will let you do it for revealed locations. So in about 1 hour (deploying now), you can enable debug mode (pressing Shift+D or using the menu bar), click "Debug" on the button under Haunted Fields and then hit reset and the connections should be all set.
