### ISSUE TITLE
Skill test modal doesn't appear when drawing encounter cards

### ISSUE THREAD

**Issue by stefano-bragaglia** [halogenandtoast/ArkhamHorror#379]
**Provide a Game ID**

The game in which I've experienced the issue is: https://arkhamhorror.app/#/games/8d512b1a-4e0e-47ca-946a-8eafdb89e559

**Describe the bug**

Every time I draw an encounter card, it takes a couple of seconds to appear in the center of the screen.
Once there it takes forever to get the interface for skill tests. Not sure if I have to click something (I don't see any visual clue).
After clicking several UI elements (without obtaining any effect), I eventually got to the skill test modal window.
Since then, I started to reload the page to force passing from the encounter card preview to the skill test window as it seems working. Not sure if the problem is because I use Safari as a browser...

**Comment by stefano-bragaglia** [comment]
I believe this also is a Safari issue (the browser I'm using).
In Chrome, the encounter card is drawn and displayed properly with a purple halo and an ok button.
By pressing the button, the modal appears immediately.

**Comment by halogenandtoast** [comment]
I've tested in Safari and I'm not seeing this issue, so either:

* It was something that got fixed in the past week
* It was a network issue?
* It was an issue with some card interaction that was slowing down the game

However I checked this game and could not create the same issue in Safari. I'm going to close this issue, BUT if you are still having it, please reopen.
