### ISSUE TITLE
Curtain Call

### ISSUE THREAD

**Issue by sedlakm-jamf** [halogenandtoast/ArkhamHorror#388]
da28435b-b0f3-444c-8a82-bd770c6d6841

Ok I wanted to end the game anyways despite the bugs but now I am super stuck. 
Cant play Act of Desperation - when I click it it says - Game out of sync.

**Comment by halogenandtoast** [comment]
The game was deleted so I can't test what happened here. I tried Act of Desperation in this scenario (agains the man in the pallid mask) and couldn't generate the issue so all I can do is close this issue since I can't make it happen again.

If you run into this issue again, please either create a new issue or reopen this one and I'll be happy to look into and fix it.
