### ISSUE TITLE
Dr. William T. Maleson

### ISSUE THREAD

**Issue by sedlakm-jamf** [halogenandtoast/ArkhamHorror#403]
953db792-0f80-4abf-9176-b16753c81cc6

cant use the guy to cancel treachery.  Critical bug.

**Comment by halogenandtoast** [comment]
@sedlakm-jamf I just tested this out and since the game is deleted I can't check if anything specific was happening here but either:

* I fixed the underlying issue in the past week
* You might not have had any clues or couldn't place clues on your location
* It was an encounter card that couldn't be cancelled for some reason.

Going to close this for now, but please let me know if you run into the issue again, either by re-opening this issue, or making a new one from the file a bug button so I have the game state.
