### ISSUE TITLE
Eucatastrophe unavailable to play when Auto Fail is pulled

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#418]
**Game ID**: e3594d12-5b87-4f6a-bf1b-3275f2483ca2

**Bug**: After pulling an Auto Fail token and choosing to not use Father Mateo's investigator ability to turn it into an Elder Sign, I was not given the opportunity to play Eucatastrophe even though my skill value was set to 0 per the Auto Fail. Not sure if this is a Eucatastrophe issue or Father Mateo issue given the steps in the above interaction.

**Comment by halogenandtoast** [comment]
I believe playing Eucatastrophe should have occurred before the elder sign ability check on Mateo, (when vs after). When I checked I saw an opportunity to play Eucatastophe even when drawing an Auto Fail token. There might have been some other reason you couldn't have played it, but it doesn't seem like your game is stopped on the exact spot were you were unable to play. I stepped back to the previous Auto Fail you drew as Mateo, but it looks like you didn't have enough resources (1 instead of 2) at that time.

If you can recreate this issue please feel free to reopen this issue or make a new one using the File a Bug feature on the site (it will snapshot it at the exact moment for me which will help).

**Comment by halogenandtoast** [comment]
No problem. Even if there isn't an issue it's great to get these reports because it could result in changes to the UI to make things more clear. There could still be an issue here of course as sometimes interactions of cards overlap in variants that cause issues.
