### ISSUE TITLE
Forced to Discard my Ally to play Mitch Brown

### ISSUE THREAD

**Issue by Jekkum** [halogenandtoast/ArkhamHorror#420]
**Provide a Game ID**
8a31ecd8-caa4-4b18-8a70-99aa8bed51af

**Describe the bug**
As Leo Anderson, I already had an ally in play and used my ability to play Mitch Brown. The game incorrectly forced me to discard the ally that I already had, even though per the FAQ Mitch's ability should allow me to have both at once, regardless of which was in play first.

**Comment by foodiemonster** [comment]
That's not a bug: Leo has a single ally slot that is occupied. Mitch Brown grants you an additional slot, but for the effect to be active he needs to already be in play. So because you don't have any ally slots to play Mitch Brown, you need to discard the other ally, THEN Mitch Brown comes into play with its effect and you could play another Ally after that.

**Comment by corwinburdick** [comment]
@foodiemonster I believe it is actually a bug. They changed/clarified this rule in an FAQ. Here's the differences (emphasis mine):

> If an investigator **is at his or her slot limit** for a type of asset and **wishes to play or gain control of** a different asset that would use that slot, the investigator must choose and discard other assets under his or her control simultaneously with the new asset entering the slot.

And now it says the following:

> If **playing or gaining control of an asset would** put an investigator **above his or her slot limit** for that type of asset, the investigator must choose and discard other assets under his or her control simultaneously with the new asset entering the slot.

The difference here is you're now allowed to play an asset if playing it gives you enough slots. For example, you can play Joe Diamond's signature guns and not discard the Magnifying Glass you have out.

**Comment by halogenandtoast** [comment]
This is a sort of regression and it used to work. The technical reason this happened is because I fixed an issue a while ago that caused the "card entered play" effect to happen multiple times, so Mitch was giving an unreasonable amount of asset slots. This was also due to a check being in place for when assets moved from out of play to in play (which was not part of the normal play an asset flow). However as a result the slot check ended up occuring after the time Mitch would have added the extra slots. 

I've put in a fix which I think covers all the cases. Specifically when you play an asset I start it off in play and then manually trigger the card entered play earlier. In the case that the card moved from an out of play area to an in play area it would trigger as part of that placement.
