### ISSUE TITLE
Unable to advance third act in Threads of Fate

### ISSUE THREAD

**Issue by FightingDoll** [halogenandtoast/ArkhamHorror#440]
**Provide a Game ID**
e03b0abf-57e9-4e48-a0f5-796c788ff002

**Describe the bug**
Act 1c is ready to advance, glowing green and the Objective button is displayed, but I can't click the button. I can't click the Advance button in debug mode either. Acts 2a and 3c work correctly.

![Objective](https://github.com/user-attachments/assets/41bc781c-276e-4ec7-8ac4-18dd9f3dab0e)

**Comment by Loerpiou** [comment]
Hey! While not a permanent solution, I've found a way to work around this issue on Chrome while Halogenandtoast codes a definitive one.

What you can do is click F12 to enable Chrome's DevTools (I'm sure there are ways to do this with other browsers, but that's what I use so not sure how you'd do it with the others).
Then, in the Layout section, you have to find div.scenario-decks. Luckily it's like the second one on the list.
Click on the little arrow on the right that redirects you to the specific code for it
Once you've done that you can go to the Computed section where you see the different space alocated to each section.
There, you can select the bottom zone for the padding square (green one for me) and give it a size. For me, 10 was enough to be able to click the Objective button.

![image](https://github.com/user-attachments/assets/508b824b-3e86-4eb4-95bf-b51f6fed2f27)


![image](https://github.com/user-attachments/assets/3b8fd3ff-97c7-49a7-80bb-1dfd0fcc3e9a)


However, I'm sorry to tell you that you won't be able to advance much after that, as another issue happens when you advance again, which I've filed an issue for here: https://github.com/halogenandtoast/ArkhamHorror/issues/443

**Comment by halogenandtoast** [comment]
I believe this is resolved now, but if you still have this issue, please reopen the issue.
