### ISSUE TITLE
Vincent Lee isn't giving out On the Mend after healing damage

### ISSUE THREAD

**Issue by mniksa3** [halogenandtoast/ArkhamHorror#461]
**Game ID**: 69695f48-0007-4687-a9f8-24eca3bf9303

**Bug**: Regardless of how Vincent Lee heals damage - Elder Sign ability, Bandages, Jessica Hyde's Reaction ability, etc. - and regardless of who that healing is for, On the Mend is not added to that investigator's hand. It's like he doesn't have an investigator ability at all :(

**Comment by halogenandtoast** [comment]
I see the issue here. I add those cards (On the Mend) to the out of play cards when the scenario begins (but hasn't been setup yet). However, the scenario is overwriting this with its own cards and so they get "deleted". This doesn't happen in every scenario because I changed how I did this which is why I didn't see the issue before.

**Comment by mniksa3** [comment]
Was just thinking it might have been because those cards are placed "out of play" during setup. And the scenario I was playing was quite unorthodox setup-wise
