### ISSUE TITLE
Aquinnah (3) doesn't always trigger.

### ISSUE THREAD

**Issue by Man-Myth-Legend** [halogenandtoast/ArkhamHorror#464]
**Provide a Game ID**
4e461727-86fb-4d72-bfff-41db652f4f89

**Describe the bug**
When a Conglomeration of Spheres attacks me during the enemy phase, the game skips right to damage assignment, even though Aquinnah(3) is ready.
This is surprising, because earlier in the scenario when a Mobster attacked, I could use Aquinnah no issue.

**Comment by mniksa3** [comment]
I had this happen in this game as well
**Game ID**: 38c12413-bdc5-4618-b7c3-59a747295719

I was able to trigger Aquinnah (3) exactly once early in the game, Since then, even though she is ready, I have only received reaction triggers for Flesh Ward even though Aquinnah's reaction triggers in the same window after an attack
