### ISSUE TITLE
Stuck in Skill Test Window

### ISSUE THREAD

**Issue by adrian-vogler** [halogenandtoast/ArkhamHorror#481]
The Skill test Window will not go away. 

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/d17d86a2a17ab495660dd73d15f9346eb89a1ec6fcb3f0dd45c58db3aa307ddb.json

**Comment by halogenandtoast** [comment]
I think the issue here is you play shortcut and you need to move an investigator. After clicking an investigator, you need to click the location, but the skill test window is covering it up. You should be able to drag it out of the way. Soon I'll add some way to hide the window (or maybe even auto hide it), but I'm trying to get through the backlog of issues first.

If you are dragging the window around and it doesn't fix your issue, please feel free to reopen this.
