### ISSUE TITLE
Drawn Curse tokens do not subtract from skill value

### ISSUE THREAD

**Issue by grabben2** [halogenandtoast/ArkhamHorror#520]
Drew 2 curse tokens and a -1 on a 5 on 3 difficulty skill test. Succeeded by 1, should have failed by 3.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/56b4d0e5fd06aa8722fe24bf05d9c36ed55600a6a18c5c011e209292ed2cb060.json

**Comment by halogenandtoast** [comment]
The issue here is that Accursed didn't correctly set itself as being in Limbo and as a result, wasn't "removed" when the skill test it was committed to finished. So all of those curse tokens had a "count as 0" modifier on them. I've fixed Accursed but it would be difficult to fix it within your current game.

Thanks a lot for your bug report, not sure I would have noticed this otherwise!
