### ISSUE TITLE
Jessica Hyde allowed me to trigger her ability twice

### ISSUE THREAD

**Issue by p-sin** [halogenandtoast/ArkhamHorror#534]
https://arkhamhorror.app/#/games/0d2bbc35-20a7-4757-8007-e11b838acdb2

Been using her throughout, but on one turn, it let me trigger her ability twice. Not sure what was different this time. She was exahusted (but pretty sure she's been exhausted and I've used the ability previously)

**Comment by halogenandtoast** [comment]
There was an issue before where reactions might have not worked correctly for a day or so. This might have been the issue. I can't tell because this game was deleted, but the Jessica Hyde code looks correct so I am hoping that was it. If you come across this issue again, please feel free to reopen this bug.
