### ISSUE TITLE
Sefina Underneath cards

### ISSUE THREAD

**Issue by dbennefield** [halogenandtoast/ArkhamHorror#583]
Sefina cannot play or draw her cards placed underneath at start of game

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/d94c67ddd6e0c340fab99a70b0f6baa3fd3a60f43b5f8cdc8a784a6bac3089ed.json

**Comment by halogenandtoast** [comment]
I didn't have an issue with this. To draw her cards you need to use her ability or to play them use the painted world. 

NOTE: The cards underneath don't automatically show themselves, you need to click the button "Underneath (x)" in order to see them.

Feel free to reopen this if you are still having the issue.
