### ISSUE TITLE
Cannot advance Agenda after STA adds Doom

### ISSUE THREAD

**Issue by NovamationCEO** [halogenandtoast/ArkhamHorror#596]
The Silver Twilight Acolyte added a doom to Agenda 1, raising it to 7 doom.  At this point, it flips to 1b immediately, then freezes without asking for further input - as best as we can tell.  

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/43a026e6c044ff94c1b29a10e0c8a8bda0c572442728a93331c6b960b955e79c.json

On the whole, however, this is an incredible app.

**Comment by halogenandtoast** [comment]
This seems okay to me (at least now). It doesn't actually flip immediately, but since nothing happens between ending the round and the agenda advancing in the Mythos phase it ends up jumping directly there. When I went to debug this, I was able to click the agenda, and then it prompted me to deal horror to the investigators by clicking their horror tokens.

I might have fixed something between you opening the issue and me checking it so let me know if you are still running into this issue.
