### ISSUE TITLE
Inscription of the hunt takes two charges

### ISSUE THREAD

**Issue by p-sin** [halogenandtoast/ArkhamHorror#617]
Activating inscription of the hunt consumes two charges of the runic axe

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/5e7d7c3d2f7d4afafa7297a3493665949970037406e8411edf878c06637a871d.json

**Comment by halogenandtoast** [comment]
If it's because you are going after Seeker of Carcosa, you need to spend two, one to move, and one to engage as the hunt ability is an or not an and. I tried it on another enemy and it spent 1 correctly.

Going to close this one, but let me know if you are still having an issue and perhaps I misunderstood.

**Comment by p-sin** [comment]
Ahh, they are aloof, of course. You made the game too clever for me!
