### ISSUE TITLE
cant load new decks

### ISSUE THREAD

**Issue by castoryayo** [halogenandtoast/ArkhamHorror#653]
I cant load new decks, neither from url or file

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/a0b7e71d394c73049242114646d4a30896b8a2b38309eebe2803b36b7f6890a0.json

**Comment by halogenandtoast** [comment]
I've looked into debugging this and I don't know what causes this (I do see what the problem is though). What is essentially happening is the game thinks your player id is something it shouldn't be and it's failing. Under normal conditions this should not happen. Your only option in this particular case is to make a new game (even if I were to fix the issue, this would not be recoverable). I'll keep looking into this issue though.

**Comment by castoryayo** [comment]
I have tried to create a new game. I have deleted everything (games and
decks) and started again, but it still won't let me load decks.
I'll try to create a new user to see what happens.
I will inform you about it.
Thank you
All the best

**Comment by foodiemonster** [comment]
I've just encountered this same issue, tried to load a new deck from ArkhamDB and it says that the character isn't implemented yet (and it's good ol' Ashcan Pete)

**Comment by halogenandtoast** [comment]
The deck name shouldn't make any difference, do you still have the failed game? The more sample sets of this issue I have the more likely I am to discover what is going wrong.

**Comment by NovamationCEO** [comment]
Here's a possible solution that solved this issue for me:

Unless told otherwise, arkhamdb creates decks as Private, not Public.  Hitting the API for a private deck returns an incomplete payload (and a CORS error) and the message "Undefined is not implemented" (or something very close to that).  

Setting my decks to Public allowed me to paste in the URL and have the deck recognized properly by arkhamhorror.app.

**Comment by halogenandtoast** [comment]
> Here's a possible solution that solved this issue for me:
> 
> Unless told otherwise, arkhamdb creates decks as Private, not Public. Hitting the API for a private deck returns an incomplete payload (and a CORS error) and the message "Undefined is not implemented" (or something very close to that).
> 
> Setting my decks to Public allowed me to paste in the URL and have the deck recognized properly by arkhamhorror.app.

You do need your decks to be public, however, the above games were running into a different weird issues, which should be resolved now, but please reopen this issue if it is not working.
