### ISSUE TITLE
"you handle this" doesnt work

### ISSUE THREAD

**Issue by Vexerd** [halogenandtoast/ArkhamHorror#716]
90c2d2ec-32b0-42d3-9f94-abf1affc7b43

I can't chose another investigator while using this card

**Comment by halogenandtoast** [comment]
I believe I recently fixed this (5 days ago) so it should work now. Because this game progressed beyond the point of the playing of the card it's too time consuming to step back to when it was played so I'm going to assume it was the same issue. If you run into further problems with you handle this, please let me know with a new issue.
