### ISSUE TITLE
Fanatic enemy

### ISSUE THREAD

**Issue by Lucalaure** [halogenandtoast/ArkhamHorror#735]
Path to Carcosa scenario 1

Fanatic enemy completely bugged.

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/8cf120d8c163e20ea4c877c5a887b2449bfb1336d062a5a4dbc1084bba715078.json

**Comment by halogenandtoast** [comment]
I am not sure what I am looking for here, but if I had to hazard a guess I would say it was probably related to some issues I had with windows occurring multiple times in multi player games which has since been fixed. Going to assume that was the case and close this issue but if you run into any further issues with the Fanatic enemy, please reopen the issue.
