### ISSUE TITLE
Out of sync problem

### ISSUE THREAD

**Issue by Lisabo1** [halogenandtoast/ArkhamHorror#833]
And it does not let me undo

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/f612c15bf57f42d4541f61023770bd306a91c9556f42e812a56c56a915969d88.json

**Comment by Kvothe-The-Bloodless** [comment]
Not sure whether it is the case here but I have found that the out of sync error is sometimes given for something unrelated to the sync and more due to the specific setup at that moment. If so undo-ing a few times should fix things and you should stop getting the error. However, doing exactly the same thing might create the error again so you might want to bypass what you did just before. For example Stargazing (1) tends to create this situation for me when drawn. It is a bit of a hassle but you can often use debug options to get the game in more or less the correct state working around these issues. (More debug options would be great for this. Such as discarding any card from play (from any deck or hand). And perhaps even removing cards from the came.)

**Comment by halogenandtoast** [comment]
The bug here would be complicated to explain, but it should be resolved in the next deploy.

**Comment by Lisabo1** [comment]
I ve found another out of sync bug with Joey The Rat, when you trigger him without having the money to pay him plus any of your item

**Comment by halogenandtoast** [comment]
@Lisabo1 can you make a new issue for that? Either with a game id or debug file?
