### ISSUE TITLE
Alchemical Solution not drawn after successful investigation in Dunwich Legacy scenario 1

### ISSUE THREAD

**Issue by Lucalaure** [halogenandtoast/ArkhamHorror#851]
^^

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/3415bfa12609bd8635df05f357f318a06e03ab6db3db45f547619108cad69d2d.json

**Comment by halogenandtoast** [comment]
> If you have completed The House Always Wins, put the set-aside Alchemical Concoction into play underneath the Alchemy Labs. If Extracurricular Activity is the first scenario of the campaign, remove the set-aside Alchemical Concoction from the game, instead.

So the issue is that the Alchemical Concoction is not attached to the location so you can't take it. Annoyingly because I'm trying to encode these cards according to the rules, this action is still valid, but the replacement effect results in nothing happening. So to make it a bit easier to know this, I've updated the tooltip:

![Image](https://github.com/user-attachments/assets/437cdd47-358d-480b-8072-d7927aa97b51)
