### ISSUE TITLE
[TCU - The Secret Name] Game out of Sync when advancing Agenda 3b

### ISSUE THREAD

**Issue by foodiemonster** [halogenandtoast/ArkhamHorror#882]
As title, game is stuck out of sync when the agenda is meant to advance from 3b to 4a and I'm still in Act 2a. I tried to debug myself out of it by giving myself an extra action to investigate in hopes to draw the Witch House Ruins and advance the Act first but no luck (and I rather not keep cheating!)

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/3aa7548212219d9643ae53f51d6111b8857805d26080fad50f8f0f8cef8eee86.json

![image](https://github.com/user-attachments/assets/b4f658d0-4e6d-463b-9f1f-1f51b64b51f2)
![image](https://github.com/user-attachments/assets/00a9f43d-6e1e-458a-bc36-adf4bf8c5a0c)

**Comment by foodiemonster** [comment]
Safe.fromJustNote Nothing, Could not find any matches for: EnemyIs "05149"
CallStack (from HasCallStack):
fromJustNote, called at library/Arkham/Classes/Query.hs:102:22 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Classes.Query
selectJust, called at library/Arkham/Helpers/Enemy.hs:158:18 in arkham-api-0.0.0-GvXjHkRi4EEK6MwNO2vFfp:Arkham.Helpers.Enemy

file: https://arkham-horror-bugs.s3.amazonaws.com/exports/3aa7548212219d9643ae53f51d6111b8857805d26080fad50f8f0f8cef8eee86.json

**Comment by foodiemonster** [comment]
I looked at the code and I think the problem might be that it's not looking for the Enemy in the discard pile? It's looking only in OutOfPlay and SetAsideZone. Maybe something like this would help? I couldn't find any reference to the name of the Encounter Discard Pile target, so I just named it "EncounterDiscard" in the example, not sure if that's correct. Alternatively, the "OutOfPlay" definition would need to be expanded to also include the Discard?

`instance RunMessage TheWitchLight where
  runMessage msg a@(TheWitchLight attrs) = case msg of
    AdvanceAgenda aid | aid == toId attrs && onSide B attrs -> do
      -- Search for Nahab in OutOfPlay, SetAsideZone, or EncounterDiscard
      nahab <- selectJust $ enemyIs Enemies.nahab <> InOutOfPlay <> InSetAsideZone <> InEncounterDiscard
      step <- getCurrentActStep
      pushAll $ case step of
        3 ->
          [ PlaceDoom (toSource attrs) (toTarget nahab) 1
          , advanceAgendaDeck attrs
          ]
        _ ->
          [ PlaceEnemy nahab (OutOfPlay SetAsideZone)
          , advanceAgendaDeck attrs
          , PlaceDoomOnAgenda 4 CanNotAdvance
          ]
      pure a`

**Comment by halogenandtoast** [comment]
The issue with looking for an enemy in the out of play areas (like the discard), is that I don't treat them like an enemy when they are there and are instead "just cards". If you are interested in how I decided to solve this issue the diff is here:

https://github.com/halogenandtoast/ArkhamHorror/commit/5f1092c5c02c57e074059937c2cac78e561a6522

The gist is that I switched to using `getUniqueEnemyMaybe` which won't fail, and then conditionally decide to do based on whether or not we find nahab. In the case nahab isn't in play, we can find the corresponding card, obtain it, and then add it to the out of play (or in the first case just do nothing since we can't add doom to nahab).
